const projectArray = [
  {
    projectColor: "before:bg-green-800",
    projectUrl: "https://penny-pilot-bice.vercel.app/",
    projectGIT: "https://github.com/snagila/PennyPilot",
    projectGIT2: "https://github.com/snagila/penny-pilot-api",
    projectImg: "/images/PeenyPilot.png",
    projectTitle: "Penny Pilot (Full-Stack)",
    projectDescription: " Platform for user to record transactions. ",
    projectLang: [
      "TypeScript",
      "MongoDB",
      "Express",
      "React",
      "Node",
      "Redux",
      "Redux Thunk",
      "React Hook Form ",
      "BootStrapCSS",
      "JWT",
      "Bcrypt",
      "...rest",
    ],
  },
  {
    projectColor: "before:bg-green-800",
    projectUrl: "https://artistic-nepal-client-ui.vercel.app/",
    projectGIT: "https://github.com/snagila/artisticNepal_client_UI",
    projectGIT2: "https://github.com/snagila/artisticNepal_client_API",
    projectImg: "/images/AN-Client.png",
    projectTitle: "Artistic Nepal User (Full-Stack)",
    projectDescription: " Artistic Nepal e-commerce platform for user. ",
    projectLang: [
      "MongoDB",
      "Express",
      "React",
      "Node",
      "JWT",
      "Stripe",
      "Cloudinary",
      "Redux",
      "BootStrapCSS",
      "Joi",
      "Bcrypt",
      "...rest",
    ],
  },
  {
    projectColor: "before:bg-green-800",
    projectUrl: "https://artistic-nepal-admin-ui.vercel.app/",
    projectGIT: "https://github.com/snagila/artisticNepal_admin_UI",
    projectGIT2: "https://github.com/snagila/artisticNepal_admin_api",
    projectImg: "/images/AN-Admin.png",
    projectTitle: "Artistic Nepal Admin CMS (Full-Stack)",
    projectDescription: "Admin portal for Artistic Nepal e-commerce platform. ",
    projectLang: [
      "MongoDB",
      "Express",
      "React",
      "Node",
      "JWT",
      "Cloudinary",
      "Redux",
      "BootStrapCSS",
      "Joi",
      "Bcrypt",
      "...rest",
    ],
  },
  {
    projectColor: "before:bg-green-800",
    projectUrl: "https://cine-haven.vercel.app/",
    projectGIT: "https://github.com/snagila/CineHaven",
    projectImg: "/images/CineHaven.png",
    projectTitle: "CineHaven",
    projectDescription:
      "The platform allows users to search for movies, view trailers, access movie information.",
    projectLang: [
      "React",
      "BootStrapCSS",
      "Context API",
      "API Integration",
      "...rest",
    ],
  },
  {
    projectColor: "before:bg-green-800",
    projectUrl: "https://activity-ledger.vercel.app/",
    projectGIT: "https://github.com/snagila/activity-ledger",
    projectImg: "/images/Activity_Ledger.png",
    projectTitle: "Activity Ledger",
    projectDescription:
      "A simple Activity Tracker app that enables users to log and manage daily activities, with data stored locally in the app's state.",
    projectLang: ["React", "BootStrapCSS", "...rest"],
  },
  {
    projectColor: "before:bg-green-800",
    projectUrl: "https://snagila.github.io/Calculator_MyVersion/",
    projectGIT: "https://github.com/snagila/Calculator_MyVersion",
    projectImg: "/images/Calculator.png",
    projectTitle: "Calculator",
    projectDescription:
      "A basic calculator app that performs standard arithmetic operations, with all calculations handled",
    projectLang: ["React", "BootStrapCSS"],
  },
  // {
  //   projectColor: "before:bg-green-800",
  //   projectUrl: "https://sachinnagila.com/",
  //   projectGIT: "https://github.com/snagila/Sachin-Nagila",
  //   projectImg: "/images/Portfolio.png",
  //   projectTitle: "My Portfolio",
  //   projectDescription: "A portfolio website.",
  //   projectLang: ["React", "TailwindCSS"],
  // },
];

export default projectArray;
